#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 0.1.{build}
skip_tags: true
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


#---------------------------------#
#       build configuration       #
#---------------------------------#
platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true
  project: DigiByteNet.sln
  publish_nuget: true
  include_nuget_references: true

  # MSBuild verbosity level
  verbosity: normal

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    only:
      - DigiByteNet.Tests.dll